name: Rust

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-8x32-with-cache
      - nscloud-cache-tag-sov-rollup-starter-build
      - nscloud-cache-size-100gb
    steps:
      - name: TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN"

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SDK_WIP_ACCESS_TOKEN }}
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.2"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install cargo-risczero
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-risczero@1.0
      - uses: taiki-e/install-action@nextest
      - name: Install risc0-zkvm toolchain # Use the risc0 cargo extension to install the risc0 std library for the current toolchain
        shell: bash
        run: make install-risc0-toolchain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install SP1 toolchain
        shell: bash
        env:
          SHELL: /bin/bash
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make install-sp1-toolchain
      - uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: rust
      - uses: taiki-e/install-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tool: zepter@1
      - name: Check
        run: make lint
      - name: Run tests
        env:
          SP1_PROVER: "mock"
        run: cargo nextest run
      - name: Compile celestia rollup node with sp1 feature
        run: cargo build --bin node --no-default-features --features celestia_da --features sp1
      - name: Run README.md
        run: chmod +x scripts/sov-rollup-starter.sh && ./scripts/sov-rollup-starter.sh
