name: Soak Test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  SOAK_TEST_DURATION_SECONDS: 600
  MIN_EXPECTED_THROUGHPUT: 400
  MAX_EXPECTED_THROUGHPUT: 5000

jobs:
  build:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-8x32-with-cache
      - nscloud-cache-tag-sov-rollup-starter-build
      - nscloud-cache-size-100gb
    steps:
      - name: TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN"

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SDK_WIP_ACCESS_TOKEN }}
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.2"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install cargo-risczero
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-risczero@1.0
      - uses: taiki-e/install-action@nextest
      - name: Install risc0-zkvm toolchain # Use the risc0 cargo extension to install the risc0 std library for the current toolchain
        shell: bash
        run: make install-risc0-toolchain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: rust
      - name: Compile rollup node
        run: cargo build --release --bin node --no-default-features --features mock_da --features risc0
      - name: Compile soak test runner
        run: cargo build --release --bin sov-rollup-starter-soak-test

      - name: Run Soak Test Script
        shell: bash
        run: chmod +x scripts/run-soak-test.sh && ./scripts/run-soak-test.sh
